# Generated by Django 5.2.11 on 2026-05-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
    ]
