# Generated by Django 5.2.11 on 2026-04-20 12:12

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
         ('django_backend', '0002_remove_task_completed_at'),
    ]
    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailstate',
            name='last_visible_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
