# Generated by Django 5.2.11 on 2026-05-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0012_userchatsettings'),
        ('django_backend', '0014_task_completed_at_alter_drivefile_share_token'),
    ]

    operations = [
    ]
