# Generated by Django 5.2.11 on 2026-05-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0015_merge_20260518_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='link_permission',
            field=models.CharField(choices=[('VIEW', 'Viewer'), ('EDIT', 'Editor')], default='VIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='sharing_level',
            field=models.CharField(choices=[('RESTRICTED', 'Restricted'), ('ANYONE_WITH_LINK', 'Anyone with link')], default='RESTRICTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='access_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Invite'), ('LINK', 'Public Link')], default='MANUAL', max_length=10),
        ),
    ]
